addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.27")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.0.8-0.6")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.20")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.9")

addSbtPlugin("com.dwijnand"   % "sbt-dynver"   % "3.3.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.4")
//addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.0.0-M2")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"        % "1.1.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"        % "1.0.0")
addSbtPlugin("com.47deg"        % "sbt-microsites" % "0.9.0")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"   % "1.5.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"  % "1.6.0-M5")
