version: '3.7'
services:
  weddingplanner:
      container_name: weddingplanner
      image: broersen/weddingplanner-service:latest
      ports:
        - '8081'
        - '9990'
      environment:
        - "WEDDING_CONFIG=/home/librarian/conf/application.conf"
      volumes:
        - ./conf:/home/librarian/conf:ro
        - ./.data:/home/librarian/graph
      networks:
        - backend
  nginx:
    depends_on:
      - db
      - weddingplanner
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./www:/code
        - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    networks:
      - frontend
      - backend
  php:
    image: php:7-fpm
    volumes:
        - ./www:/code
    networks:
      - frontend
  db:
    build: Dockerfiles/mysql
    image: mysql:5.7
    restart: always
    volumes:
       - ./tmp/frontend_data:/var/lib/mysql
    command: ["--ignore-db-dir=lost+found", "--innodb_use_native_aio=0"]
    environment:
      MYSQL_ROOT_PASSWORD: wp_project
    networks:
      - frontend
#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: wp_project
#    networks:
#      - frontend

networks:
  frontend:
  backend:
volumes:
  frontend_data:
