version: '3.7'
services:
  weddingplanner:
      container_name: weddingplanner
      image: broersen/weddingplanner-service:latest
      restart: always
      ports:
        - '8081'
        - '9990'
      environment:
        - "WEDDING_CONFIG=/home/librarian/conf/application.conf"
      volumes:
        - ./conf:/home/librarian/conf:ro
        - ./.data:/home/librarian/graph
      networks:
        - backend
  nginx:
    depends_on:
      - weddingplanner
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
volumes:
  frontend_data:
